version: '3'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Cunplong115@
    ports:
      - "1433:1433"
    networks:
      - my-network


  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sql_server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
