version: '3'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Cunplong115@
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - mssql-data:/var/opt/mssql


  app:
    container_name: hotel
    build:
      context: .
    ports:
      - "8088:8080"
    depends_on:
      - sql_server
    networks:
      - my-network

networks:
  my-network:

volumes:
  mssql-data: